name: Build and Release

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Create build zip
        run: |
          cd dist
          zip -r ../build.zip .

      - name: Get version from package.json
        id: version
        run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.version.outputs.VERSION }}-${{ github.run_number }}
          name: Release v${{ steps.version.outputs.VERSION }}-${{ github.run_number }}
          body: |
            ## Live Update Release

            This release contains the latest build for live updates.

            **Version:** ${{ steps.version.outputs.VERSION }}-${{ github.run_number }}
            **Build Date:** ${{ github.event.head_commit.timestamp }}

            ### How to use:
            1. The app will automatically check for updates on startup
            2. If an update is available, it will be downloaded and applied
            3. The app will reload with the new version
          files: build.zip
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}